### PR TITLE
Add id to catch-all listener

### PR DESCRIPTION
**Pull request by msabramo**
Makes debugging easier when used along with https://github.com/github/hubot/pull/1074

### CODE REVIEW

**Comment by alexhouse** [comment]
I'll merge it, but will hold off on a release until Hubot issues a release as I expect this might break older clients?

**Comment by msabramo** [comment]
I don't think it will break older clients; well maybe really old ones before hubot supported passing listener options.

It seems that happened in https://github.com/github/hubot/commit/8bc2ae7c8976094910dcf5a7cafa3bfa8970f9de ?

Cc: @michaelansel, @technicalpickles

**Comment by technicalpickles** [comment]
It'll break for hubot's before listener metadata was added in 2.13.0. cc https://github.com/github/hubot/issues/1062

**Comment by michaelansel** [comment]
I think you can just update `package.json` to peerDepend on hubot >= 2.13.0

**Pull request merged**
